export const Size = {
  MODAL_TITLE_OFFSET: 30,
  MODAL_TITLE_PADDING: 40,
  MODAL_FOOTER_OFFSET: 20,
  MODAL_FOOTER_WIDTH: 200,
  MODAL_CORNER_OFFSET: 20,
  MODAL_CORNER_WIDTH: 6,
  MODAL_MIN_TITLE_WIDTH: 200,
};
