export const Size = {
  PANE_MIN_BLEED: 40,
  PANE_MIN_TITLE_WIDTH: 200,
  PANE_TITLE_OFFSET: 30,
  PANE_TITLE_PADDING: 40,
  PANE_FOOTER_OFFSET: 20,
  PANE_FOOTER_WIDTH: 200,
  PANE_CORNER_OFFSET: 20,
  PANE_CORNER_WIDTH: 6,
  SEPARATOR_MIN_DENT_WIDTH: 40,
  SEPARATOR_OFFSET: 30,
  CANVAS_CORNER_OFFSET: 60,
  CANVAS_CORNER_WIDTH: 6,
};
